// pO_electron_corrections_raw.h
//
// Z->ee electron pT scale & smearing corrections for CMS pO 9.62 TeV (2025Run3).
// Derived from {Lumi 23 nb^-1, Inclusive Z->ee, basis = raw} on 2026-05-07 21:40:17.
// Basis: GSF eleRawPt as input pT, eleSCEta as region selector.
//
// Usage:
//   #include "pO_electron_corrections_raw.h"
//   double pt_corr = pOEleCorr::raw::correctedPt(rawPt, scEta, isMC, gaussRand);
//
// gaussRand should be a standard-normal random number (mean 0, sigma 1) drawn
// fresh per electron leg. For data, gaussRand is ignored.
//
// AUTOGENERATED -- do not edit by hand. Regenerate with:
//   uv run python pO_calib/emit_corrections_cxx.py --basis raw

#pragma once
#include <cmath>

namespace pOEleCorr {
namespace raw {

// ECAL barrel/endcap boundary on supercluster eta
inline constexpr double EB_ETA_MAX = 1.4442;

// per-region pT scale factors. pT_corrected = scale * pT_input.
inline constexpr double SCALE_EB_DATA = 1.020817;  // ± 0.003053
inline constexpr double SCALE_EE_DATA = 1.087120;  // ± 0.012531
inline constexpr double SCALE_EB_MC   = 0.996921;
inline constexpr double SCALE_EE_MC   = 0.993451;

// MC-only relative pT smearing (sigma per leg). pT *= 1 + gaussRand * smear.
inline constexpr double SMEAR_EB = 0.009815;  // ± 0.008015
inline constexpr double SMEAR_EE = 0.053355;  // ± 0.010398

// post-correction closure (data peak vs M_Z), as fractional residuals
inline constexpr double CLOSURE_EB = -0.000029;
inline constexpr double CLOSURE_EE = -0.001656;

inline bool isEB(double scEta) noexcept {
    return std::abs(scEta) < EB_ETA_MAX;
}

inline double scaleData(double scEta) noexcept {
    return isEB(scEta) ? SCALE_EB_DATA : SCALE_EE_DATA;
}

inline double scaleMC(double scEta) noexcept {
    return isEB(scEta) ? SCALE_EB_MC : SCALE_EE_MC;
}

inline double smearWidth(double scEta) noexcept {
    return isEB(scEta) ? SMEAR_EB : SMEAR_EE;
}

// One-shot: apply scale and (for MC) Gaussian smearing.
//   isMC       : true on simulation, false on data.
//   gaussRand  : standard-normal random; ignored for data.
inline double correctedPt(double rawPt, double scEta, bool isMC,
                          double gaussRand = 0.0) noexcept {
    double pt = rawPt * (isMC ? scaleMC(scEta) : scaleData(scEta));
    if (isMC) pt *= (1.0 + gaussRand * smearWidth(scEta));
    return pt;
}

// Dilepton invariant mass with corrections applied. Inputs are RAW (uncorrected)
// per-leg pT/eta/phi, plus the SC eta of each leg for region assignment.
//   gauss1, gauss2 : independent standard-normal draws per leg.
inline double correctedMee(double rawPt1, double eta1, double phi1, double scEta1,
                           double rawPt2, double eta2, double phi2, double scEta2,
                           bool isMC,
                           double gauss1 = 0.0, double gauss2 = 0.0) noexcept {
    constexpr double m_e = 0.000511;
    const double pt1 = correctedPt(rawPt1, scEta1, isMC, gauss1);
    const double pt2 = correctedPt(rawPt2, scEta2, isMC, gauss2);
    const double e1  = std::sqrt(pt1*pt1*std::cosh(eta1)*std::cosh(eta1) + m_e*m_e);
    const double e2  = std::sqrt(pt2*pt2*std::cosh(eta2)*std::cosh(eta2) + m_e*m_e);
    const double pz1 = pt1 * std::sinh(eta1);
    const double pz2 = pt2 * std::sinh(eta2);
    const double px = pt1*std::cos(phi1) + pt2*std::cos(phi2);
    const double py = pt1*std::sin(phi1) + pt2*std::sin(phi2);
    const double pz = pz1 + pz2;
    const double e  = e1 + e2;
    const double m2 = e*e - (px*px + py*py + pz*pz);
    return m2 > 0 ? std::sqrt(m2) : 0.0;
}

}  // namespace raw
}  // namespace pOEleCorr
